# Generated by Django 5.2 on 2025-04-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(choices=[('AR', 'Argentina'), ('ES', 'España'), ('MX', 'Mexico')], max_length=2)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_fallecimiento', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
